sudo: required
#since we are using docker

services:
  - docker

before_install:
  - docker build -t akashmane15/docker-react -f Dockerfile.dev .

script:
  - docker run --env CI=true akashmane15/docker-react npm run test -- --coverage
